version: '3.7'

services:
  laravel-app:
    container_name: controle_de_vendas
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8000"
    volumes:
      - ./:/app
    depends_on:
    - mysql-app
    networks:
      - app-network

  mysql-app:
    image: mysql:5.7.22
    restart: always
    volumes:
      - .dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:3306
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
